name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install -y python3-pip python3-dev build-essential git \
            libgl1-mesa-dev libgles2-mesa-dev libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev libgstreamer1.0-gtk3-dev \
            gstreamer1.0-tools gstreamer1.0-gtk3 \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
            libsdl2-ttf-dev libportmidi-dev libswscale-dev \
            libavformat-dev libavcodec-dev ffmpeg libgmp-dev

    - name: Install Buildozer
      run: |
        pip install buildozer

    - name: Build APK
      run: |
        buildozer -v android debug
        buildozer android deploy run
